export const ADD_COMMENT = 'ADD_COMMENT'
export const COMMENTS_FAILED = 'COMMENTS_FAILED'
export const ADD_COMMENTS = 'ADD_COMMENTS'


export const DISHES_LOADING = 'DISHES_LOADING'
export const DISHES_SUCCESS = 'DISHES_SUCCESS'
export const DISHES_FAILED = 'DISHES_FAILED'
export const ADD_DISHES = 'ADD_DISHES'


export const DISH_WITH_ID_LOADING = 'DISH_WITH_ID_LOADING'
export const DISH_WITH_ID_SUCCESS = 'DISH_WITH_ID_SUCCESS'
export const DISH_WITH_ID_FAILED = 'DISH_WITH_ID_FAILED'


export const GET_FAVORITES_LOADING = 'GET_FAVORITES_LOADING'
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS'
export const GET_FAVORITES_FAILED = 'GET_FAVORITES_FAILED'

export const ADD_FAVORITE_LOADING = 'ADD_FAVORITE_LOADING'
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS'
export const ADD_FAVORITE_FAILED = 'ADD_FAVORITE_FAILED'

export const DELETE_FAVORITE_LOADING = 'DELETE_FAVORITE_LOADING'
export const DELETE_FAVORITE_SUCCESS = 'DELETE_FAVORITE_SUCCESS'
export const DELETE_FAVORITE_FAILED = 'DELETE_FAVORITE_FAILED'



export const RESERVATIONS_LOADING = 'RESERVATIONS_LOADING'
export const RESERVATIONS_SUCCESS = 'RESERVATIONS_SUCCESS'
export const RESERVATIONS_FAILED = 'RESERVATIONS_FAILED'

export const ADD_RESERVATION_LOADING = 'ADD_RESERVATION_LOADING'
export const ADD_RESERVATION_SUCCESS = 'ADD_RESERVATION_SUCCESS'
export const ADD_RESERVATION_FAILED = 'ADD_RESERVATION_FAILED'



// comment
export const ADD_COMMENT_LOADING = 'ADD_COMMENT_LOADING'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED'



export const DELETE_COMMENT_LOADING = 'DELETE_COMMENT_LOADING'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED'







export const PROMOS_LOADING = 'PROMOS_LOADING'
export const PROMOS_SUCCESS = 'PROMOS_SUCCESS'
export const PROMOS_FAILED = 'PROMOS_FAILED'
export const ADD_PROMOS = 'ADD_PROMOS'

export const LEADERS_LOADING = 'LEADERS_LOADING'
export const LEADERS_SUCCESS = 'LEADERS_SUCCESS'
export const LEADERS_FAILED = 'LEADERS_FAILED'


export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'

export const LOGOUT_USER = 'LOGOUT_USER'

export const REGISTER_USER_LOADING = 'REGISTER_USER_LOADING'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'